### ISSUE TITLE
Tag releases and publish release notes on GitHub

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/vscode-ai-toolkit#100]
It would be very helpful if you tagged releases on the public GitHub when you released to the Extension Marketplace and included release notes here. This was those of us who follow the project on GitHub will get a notification here when a new release is provided, in addition to in-app.

**Comment by potatoqualitee** [comment]
Yes pls

**Comment by swatDong** [comment]
@sffamily - any concern or thought if adding the release notes to this doc repo?

**Comment by GitMensch** [comment]
... or, even better, make the extension itself available #72 - as this includes the Changelog.md and tags without additional work.

**Comment by sffamily** [comment]
Now we have What's New notes with each major release, so from VS Code it will pop-up, but some links we found we need to fix, as well as repos. Thank you for pointing them out!

**Comment by sffamily** [comment]
As said with each new release, we follow the VS Code extension release convention to also publish What's new doc, as the release log. So close this.
