### ISSUE TITLE
extension license issue

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode-ai-toolkit#110]
Seems the the license was not updated since its initial release and then was only copied.

https://marketplace.visualstudio.com/items/ms-windows-ai-studio.windows-ai-studio/license

currently says:

> MICROSOFT **LIVE SHARE EXTENSION** FOR VISUAL STUDIO FAMILY OF PRODUCTS
>
>These license terms are an agreement between you and Microsoft Corporation (or based on where you live, one of its affiliates). They apply to the software named above.

I therefore have to conclude that there is currently no license for the use of the extension at all :-/

And when you adjust this, please replace the restriction under "INSTALLATION AND USE RIGHTS", which currently reads

> You may install and use any number of copies of the software to use solely with Microsoft Visual Studio family of products.

by something like

> You may install and use any number of copies of the software to use solely with Microsoft Visual Studio Code or derivatives thereof.

[reasoning: it is already documented to need vscode - not any other Visual Studio products - and there is otherwise no option to run it with self-built versions of vscode]

**Comment by shangzd** [comment]
@GitMensch Thank you for the feedback, and we are working with Licensing and legal team to update it.

**Comment by sffamily** [comment]
@GitMensch Thank you for your feedback, we've been working with our licensing and legal team to update it.

**Comment by sffamily** [comment]
This should have been replaced with updated license, so closing this.
