### ISSUE TITLE
how can I use ollama?

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/vscode-ai-toolkit#114]
how can I connect to ollama?
I try to use url as in documentaion http://localhost:11434/api/chat but this is not working

**Comment by a1exwang** [comment]
As the document states,
> Use "http://localhost:11434/v1/chat/completions" as URL and leave auth empty

The URL should be `http://localhost:11434/v1/chat/completions`, not `http://localhost:11434/api/chat`
