### ISSUE TITLE
When creating a project and opening the workspace in WSL, some file are not in UTF-8

### ISSUE THREAD

**Issue by questmapping** [microsoft/vscode-ai-toolkit#117]
The two files that give this problem are setup/conda-environment.yml and setup/olive_ai-0.7.0-py3-none-any.whl

as an example I'm attaching a screenshot
![Image](https://github.com/user-attachments/assets/5eddf9e7-677b-49f6-b48e-d99f2683811f)

the first file can be recovered by changing from utf8 to utf16le and saving back to utf8, while the second file no.

**Comment by questmapping** [comment]
Also moved the whl file inside the setup/setup folder and got this error

`Creating or resetting Conda environment from ./setup/conda-environment.yml...
/opt/miniconda/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Channels:
 - pytorch
 - nvidia
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/opt/miniconda/envs/phi-2/bin/python', '-m', 'pip', 'install', '-U', '-r', '/mnt/c/LLM/Fine Tuning/phinetune/setup/condaenv.8srnrod5.requirements.txt', '--exists-action=b']
Pip subprocess output:
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu124
Processing ./setup/olive_ai-0.7.0-py3-none-any.whl (from -r /mnt/c/LLM/Fine Tuning/phinetune/setup/requirements.txt (line 22))

Pip subprocess error:
ERROR: Wheel 'olive-ai' located at /mnt/c/LLM/Fine Tuning/phinetune/setup/setup/olive_ai-0.7.0-py3-none-any.whl is invalid.

failed

CondaEnvException: Pip failed

Script execution completed.`

is there a pip package I can put in the requirements.txt instead of the whl?

**Comment by Blazehouse** [comment]
I'm also getting this error.
Changing the encoding from UTF8 to UTF16le and then back, did not work for me.

`
./first_time_setup.sh 
no change     /opt/miniconda/condabin/conda
no change     /opt/miniconda/bin/conda
no change     /opt/miniconda/bin/conda-env
no change     /opt/miniconda/bin/activate
no change     /opt/miniconda/bin/deactivate
no change     /opt/miniconda/etc/profile.d/conda.sh
no change     /opt/miniconda/etc/fish/conf.d/conda.fish
no change     /opt/miniconda/shell/condabin/Conda.psm1
no change     /opt/miniconda/shell/condabin/conda-hook.ps1
no change     /opt/miniconda/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /opt/miniconda/etc/profile.d/conda.csh
no change     /home/jacob/.bashrc
No action taken.
Creating or resetting Conda environment from ./conda-environment.yml...
/opt/miniconda/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/cli/main.py", line 61, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 205, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/cli/main_env_create.py", line 121, in execute
        spec = specs.detect(
               ^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/deprecations.py", line 174, in inner
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/env/specs/__init__.py", line 64, in detect
        if spec.can_handle():
           ^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/env/specs/yaml_file.py", line 19, in can_handle
        self._environment = env.from_file(self.filename)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/env/env.py", line 173, in from_file
        return from_yaml(yamlstr, filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/env/env.py", line 139, in from_yaml
        data = yaml_safe_load(yamlstr)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/conda/common/serialize.py", line 46, in yaml_safe_load
        return _yaml_safe().load(string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/ruamel/yaml/main.py", line 449, in load
        constructor, parser = self.get_constructor_parser(stream)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/ruamel/yaml/main.py", line 500, in get_constructor_parser
        self.reader.stream = stream
        ^^^^^^^^^^^^^^^^^^
      File "/opt/miniconda/lib/python3.12/site-packages/ruamel/yaml/reader.py", line 107, in stream
        self.check_printable(val)
      File "/opt/miniconda/lib/python3.12/site-packages/ruamel/yaml/reader.py", line 221, in check_printable
        raise ReaderError(
    ruamel.yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "<unicode string>", position 3

`$ /opt/miniconda/bin/conda env create -f ./conda-environment.yml`
`

**Comment by dbon-gh** [comment]
- Change conda-environment.yml to utf-16 LE 
- Remove the first three signs
 ![Image](https://github.com/user-attachments/assets/d0f53bd7-c0f9-4e61-9292-2caadb5a5aec)

- Save file
- Comment olive whl in requirements
#./setup/olive_ai-0.7.0-py3-none-any.whl
- Install olive-ai by pip install olive-ai
- Run ./setup/first_time_setup.sh
- Run python finetuning/invoke_olive.py
- Then the errors occurred 
-- ModuleNotFoundError: No module named 'datasets' > pip install datasets
-- ModuleNotFoundError: No module named 'onnxruntime' > pip install onnxruntime
-- ModuleNotFoundError: No module named 'bitsandbytes' > pip install bitsandbytes
-- ModuleNotFoundError: No module named 'peft' > pip install peft
- Run python finetuning/invoke_olive.py again

it is still running so i do not know if it is fixed now

**Comment by XiaofuHuang** [comment]
Thank you for the report. We are currently working on resolving this issue.

**Comment by XiaofuHuang** [comment]
The bug has been fixed in v0.8.2.
