### ISSUE TITLE
Ollama: llama3.2-vision not taking attachments

### ISSUE THREAD

**Issue by KikeVen** [microsoft/vscode-ai-toolkit#139]
I can not load the vision model from Ollama, because the ai-toolkit interface does not allow me to select an image.

![Image](https://github.com/user-attachments/assets/e30c67ce-9879-4432-997d-d0a36bdfdfa9)

**Comment by kuojianlu** [comment]
Fixed in https://github.com/microsoft/Skylight/pull/1053. Will be shipped in next release.
