### ISSUE TITLE
Why does the extension needs to access GitHub org data

### ISSUE THREAD

**Issue by sutharzan-ch** [microsoft/vscode-ai-toolkit#71]
Hi,
Is it possible to let me know why it is prompting me to authenticate to my GitHub org during and attempting to access my org data. Based on the doc https://github.com/microsoft/vscode-ai-toolkit/blob/main/QA.md  the auth is needed to pull templates and the templates are not in my org. I would also like to know what data from my GitHub and my org will be shared with MS and others during this process. Will any one my code or other files open in VSC will be sent MS or other parties during the use of this extension?

Thanks!

**Comment by swatDong** [comment]
AI Toolkit collects usage data and sends it to Microsoft to help improve the product.
No account info or org info is sent.
See [Privacy Statement](https://go.microsoft.com/fwlink/?LinkId=521839) to learn more.
