### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by sovereignstack** [microsoft/vscode-ai-toolkit#72]
Where is the source code? I can only see markdown files and images
![image](https://github.com/microsoft/vscode-ai-toolkit/assets/3187668/f080828b-5dc0-4138-98ed-17f6ec9816f8)

**Comment by jflam** [comment]
The toolkit is not as of yet open source. The GH repo is being used for public issue tracking for now.

**Comment by swatDong** [comment]
Answering auth issue [here](https://github.com/microsoft/vscode-ai-toolkit/issues/71).
Closing this one.

**Comment by GitMensch** [comment]
Can you please reopen this and make it sticky and/or add information to this repos README?

> The toolkit is not as of yet open source. The GH repo is being used for public issue tracking for now.

Having more details on that public would definitely be welcomed...
