### ISSUE TITLE
olive-config.json generated with wrong decimal separator

### ISSUE THREAD

**Issue by sebug** [microsoft/vscode-ai-toolkit#73]
On Windows with Regional format French (Switzerland), when running the model fine-tuning wizard, the generated config file olive-config.json is not valid JSON - it uses the comma instead of the dot as decimal separator for float values in the JSON:

[snip]
    "passes": {
        "qlora": {
            "type": "QLoRA",
            "config": {
                "compute_dtype": "bfloat16",
                "quant_type": "nf4",
                "double_quant": true,
                "lora_r": 64,
                "lora_alpha": 64,
                "lora_dropout": 0,1,
                "train_data_config": "dataset_default_train",
                "eval_dataset_size": 0,3,
                "training_args": {
                    "seed": 0,
                    "data_seed": 42,

[snip]

note the "lora_dropout": 0,1

**Comment by swatDong** [comment]
@sebug could you please try the newer version (`0.3.2`) of the extension? It should be already fixed.

**Comment by sebug** [comment]
Hello, yes, I confirm that with version v0.3.2 pre-release the generated JSON is valid. Thanks.
