### ISSUE TITLE
Apple Silicon and Linux support

### ISSUE THREAD

**Issue by marlinspike** [microsoft/vscode-ai-toolkit#77]
Need Apple Silicon and Linux support please!

**Comment by sffamily** [comment]
They are being worked on (priority given to Apple Silicon) right now and we target July to preview them if all tests are ok.

**Comment by potatoqualitee** [comment]
Shipped! I installed it and it works wonderfully.

**Comment by pvy** [comment]
The 'AI Toolkit for Visual Studio Code' extension is not available in Visual Studio Code for Linux ARM 64.
 (asahi fedora linux with m1)

**Comment by GitMensch** [comment]
The extension README says

> AI Toolkit will run on Windows, Mac and Linux.

So it seems this issue can be closed-fixed?

Note: It does not say anything specific about the CPU or OS. _If_ it is only available as "native" extension, then the README should get an update for that - and glibc-ARM64 would be nice (but that's still a separate issue then).

**Comment by lc3t35** [comment]
Please support Intel OSX

**Comment by GitMensch** [comment]
Note (as this is what I'm going for): if you want to start using local LLM, you may do so on all environments with the [`Continue.continue` extension](https://github.com/continuedev/continue/tree/main). That's of course _a bit_ more setup to do, but you definitely have the complete control on the way and full code for the extension (licensed under Apache 2.0) and, of course, an extension that works out-of-the box on any "fat vscode" client (not only the MS builds) and is also available outside of the MS marketplace.

**Comment by sffamily** [comment]
@lc3t35 Intel Mac support has been added and will be release around Thanksgiving.

**Comment by sffamily** [comment]
Since both requested platforms are now supported in formal releases, close this.
