### ISSUE TITLE
Inference in AI project not working

### ISSUE THREAD

**Issue by liorbalmas** [microsoft/vscode-ai-toolkit#82]
Project's Readme says that 
`python gradio_chat.py --baseonly `
should start a local web server for inference
but the command generates this error:
```
 torch_dtype = torch.<compute_dtype>  # Set the appropriate torch data type
                        ^
SyntaxError: invalid syntax
```

it seems like compute_dtype is an input parameter that should be provided by the user after the page and model are loaded

**Comment by swatDong** [comment]
@liorbalmas - how was the project generated? Did you meet any issue during the "**Generate Project**" step? (the step looks like)
<img width="635" alt="image" src="https://github.com/microsoft/vscode-ai-toolkit/assets/7642967/d7029e2a-f25a-46a3-b036-4ffbca3ecf55">

There are several place holders ("<*xxx_xxx*>") in the draft project and are replaced in the "**Generate Project**" step.

**Comment by liorbalmas** [comment]
yes. I went through that screen  and it went smooth.
But the paths here do not exist
<img width="413" alt="image" src="https://github.com/microsoft/vscode-ai-toolkit/assets/21119451/18d969c0-7a35-42cf-a069-5f5fff8aa208">

additionally, the python environment was not created in WSL. the README assumes it is as it says to runconda activate [conda-env-name]  but the environment wasn't created...

**Comment by liorbalmas** [comment]
I am using anaconda. It's installed directly under  c:\
I gave full permissions to my user to anaconda's folder, and now models are created  (project generation takes much more time, I can see it downloads them) and when it finishes, on click on the button to open the project, it opens in WSL as expected. So far so good
Now I notice 2 problems
1) the python env was not created during project creation
2) the requirements.txt is empty -  Is that ok?

Thanks

**Comment by liorbalmas** [comment]
![image](https://github.com/microsoft/vscode-ai-toolkit/assets/21119451/3c01b6ed-ef67-4d2b-a4b8-95158251bb64)

**Comment by liorbalmas** [comment]
The issue seems to be my wsl distro (ubuntu) cannot access the internet
restarting doesn't help
Trying to fix that..

Would have been helpful if AI toolkit project had checked that and displayed a clear error message

**Comment by swatDong** [comment]
Thanks for the good suggestion to add network to prerequisites check. Added to backlog.

Closing as the original issue resolved.
