### ISSUE TITLE
how to remove installed model?

### ISSUE THREAD

**Issue by DingpingZhang** [microsoft/vscode-ai-toolkit#85]
I downloaded a mistral AI model, but now I want to delete this model.
However, I've searched through the entire UI and couldn't find any way to remove this model.
![image](https://github.com/user-attachments/assets/bd6f59f8-a347-42ff-8677-a77d2701f05d)

**Comment by swatDong** [comment]
Currently there's no *delete* command from VSC, but you can go `{$HOME}/.aitk/models/` folder to delete the model folder manually.

**Comment by DingpingZhang** [comment]
thx, resolved
