### ISSUE TITLE
GitHub Marketplace Models for Remote Inference

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/vscode-ai-toolkit#98]
Hello,
How can I make GitHub models work with AI Toolkit?

![image](https://github.com/user-attachments/assets/6cc2e165-48ed-442b-b8ca-1214d818ebcb)

![image](https://github.com/user-attachments/assets/e05eb98f-b361-4aff-9ac3-e937a43b975a)

Perhaps it's bc I cannot append the model name to the body as the example suggests.

```
curl -X POST "https://models.inference.ai.azure.com/chat/completions" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -d '{
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "What is the capital of France?"
            },
            {
                "role": "assistant",
                "content": "The capital of France is Paris."
            },
            {
                "role": "user",
                "content": "What about Spain?"
            }
        ],
        "model": "gpt-4o-mini"
    }'
```

**Comment by swatDong** [comment]
The latest pre-release of AI Toolkit has integrated GitHub models in model catalog.
(cc @a1exwang if I missed anything)

Please try:
1. Install latest pre-release
    <img width="523" alt="image" src="https://github.com/user-attachments/assets/3118ad89-3cf0-456c-885d-87336ad1b12a">

1. Open `Model Catalog`
    <img width="656" alt="image" src="https://github.com/user-attachments/assets/3a6f591b-becd-46a8-80de-5ee521758354">

1. Add and try GitHub models in playground
    <img width="679" alt="image" src="https://github.com/user-attachments/assets/4eaec2ff-dce5-43cb-8b2a-0bb8fd623e2c">

**Comment by potatoqualitee** [comment]
Oh! Didn't realize these were from GitHub. Does this count against our github.com/marketplace models limits?

https://docs.github.com/en/github-models/prototyping-with-ai-models#rate-limits

Can people who don't have preview access to the model marketplace access it via AI Toolkit?

**Comment by swatDong** [comment]
> Oh! Didn't realize these were from GitHub. Does this count against our github.com/marketplace models limits?
> 
> https://docs.github.com/en/github-models/prototyping-with-ai-models#rate-limits
> 
> Can people who don't have preview access to the model marketplace access it via AI Toolkit?

Opening model in AI Toolkit shares the same access&limit as opening on GitHub.
If signing in an account in VSCode without preview access, you cannot chat with those models in AI Toolkit.
<img width="336" alt="image" src="https://github.com/user-attachments/assets/30180a37-b6dc-4a61-9a28-ccbec9c41cfa">

**Comment by potatoqualitee** [comment]
Merci 👍🏼
